"""保存了一个数据集中的AST，用以进行测试"""

ast_example = [{'id': 0, 'type': 'Program', 'children': [1]},
                   {'id': 1, 'type': 'ExpressionStatement', 'children': [2]},
                   {'id': 2, 'type': 'CallExpression', 'children': [3, 8, 9, 10]},
                   {'id': 3, 'type': 'MemberExpression', 'children': [4, 7]},
                   {'id': 4, 'type': 'MemberExpression', 'children': [5, 6]},
                   {'id': 5, 'type': 'Identifier', 'value': 'CKEDITOR'},
                   {'id': 6, 'type': 'Property', 'value': 'plugins'},
                   {'id': 7, 'type': 'Property', 'value': 'setLang'},
                   {'id': 8, 'type': 'LiteralString', 'value': 'iframe'},
                   {'id': 9, 'type': 'LiteralString', 'value': 'ka'},
                   {'id': 10, 'type': 'ObjectExpression', 'children': [11, 13, 15, 17, 19]},
                   {'id': 11, 'type': 'Property', 'value': 'border', 'children': [12]},
                   {'id': 12, 'type': 'LiteralString', 'value': 'ჩარჩოს გამოჩენა'},
                   {'id': 13, 'type': 'Property', 'value': 'noUrl', 'children': [14]},
                   {'id': 14, 'type': 'LiteralString', 'value': 'აკრიფეთ iframe-ის URL'},
                   {'id': 15, 'type': 'Property', 'value': 'scrolling', 'children': [16]},
                   {'id': 16, 'type': 'LiteralString', 'value': 'გადახვევის ზოლების დაშვება'},
                   {'id': 17, 'type': 'Property', 'value': 'title', 'children': [18]},
                   {'id': 18, 'type': 'LiteralString', 'value': 'IFrame-ის პარამეტრები'},
                   {'id': 19, 'type': 'Property', 'value': 'toolbar', 'children': [20]},
                   {'id': 20, 'type': 'LiteralString', 'value': 'IFrame'}, 0]


binary_tree = [{'id': 0,
                  'type': 'Program',
                  'children': [1],
                  'right': -1,
                  'isTerminal': False,
                  'hasNonTerminalChild': True,
                  'hasSibling': False,
                  'left': 1},
                 {'id': 1,
                  'type': 'ExpressionStatement',
                  'children': [2],
                  'right': -1,
                  'isTerminal': False,
                  'hasNonTerminalChild': True,
                  'hasSibling': False,
                  'left': 2},
                 {'id': 2,
                  'type': 'CallExpression',
                  'children': [3, 8, 9, 10],
                  'right': -1,
                  'isTerminal': False,
                  'hasNonTerminalChild': True,
                  'hasSibling': False,
                  'left': 3},
                 {'id': 3,
                  'type': 'MemberExpression',
                  'children': [4, 7],
                  'right': 8,
                  'isTerminal': False,
                  'hasNonTerminalChild': True,
                  'hasSibling': True,
                  'left': 4},
                 {'id': 4,
                  'type': 'MemberExpression',
                  'children': [5, 6],
                  'right': 7,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': True,
                  'left': 5},
                 {'id': 5,
                  'type': 'Identifier',
                  'value': 'CKEDITOR',
                  'right': 6,
                  'isTerminal': True},
                 {'id': 6,
                  'type': 'Property',
                  'value': 'plugins',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 7,
                  'type': 'Property',
                  'value': 'setLang',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 8,
                  'type': 'LiteralString',
                  'value': 'iframe',
                  'right': 9,
                  'isTerminal': True},
                 {'id': 9,
                  'type': 'LiteralString',
                  'value': 'ka',
                  'right': 10,
                  'isTerminal': True},
                 {'id': 10,
                  'type': 'ObjectExpression',
                  'children': [11, 13, 15, 17, 19],
                  'right': -1,
                  'isTerminal': False,
                  'hasNonTerminalChild': True,
                  'hasSibling': False,
                  'left': 11},
                 {'id': 11,
                  'type': 'Property',
                  'value': 'border',
                  'children': [12],
                  'right': 13,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': True,
                  'left': 12},
                 {'id': 12,
                  'type': 'LiteralString',
                  'value': 'ჩარჩოს გამოჩენა',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 13,
                  'type': 'Property',
                  'value': 'noUrl',
                  'children': [14],
                  'right': 15,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': True,
                  'left': 14},
                 {'id': 14,
                  'type': 'LiteralString',
                  'value': 'აკრიფეთ iframe-ის URL',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 15,
                  'type': 'Property',
                  'value': 'scrolling',
                  'children': [16],
                  'right': 17,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': True,
                  'left': 16},
                 {'id': 16,
                  'type': 'LiteralString',
                  'value': 'გადახვევის ზოლების დაშვება',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 17,
                  'type': 'Property',
                  'value': 'title',
                  'children': [18],
                  'right': 19,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': True,
                  'left': 18},
                 {'id': 18,
                  'type': 'LiteralString',
                  'value': 'IFrame-ის პარამეტრები',
                  'right': -1,
                  'isTerminal': True},
                 {'id': 19,
                  'type': 'Property',
                  'value': 'toolbar',
                  'children': [20],
                  'right': -1,
                  'isTerminal': False,
                  'hasNonTerminalChild': False,
                  'hasSibling': False,
                  'left': 20},
                 {'id': 20,
                  'type': 'LiteralString',
                  'value': 'IFrame',
                  'right': -1,
                  'isTerminal': True},
                 'EOF']


nt_sequence_example = [('MemberExpression=$$=True=$$=False4', 'Identifier=$$=CKEDITOR==5'),
                         ('MemberExpression=$$=True=$$=False4', 'Property=$$=plugins==6'),
                         ('MemberExpression=$$=True=$$=True3', 'EMPTY'),
                         ('MemberExpression=$$=True=$$=True3', 'Property=$$=setLang==7'),
                         ('Property=$$=True=$$=False11', 'LiteralString=$$=ჩარჩოს გამოჩენა==12'),
                         ('Property=$$=True=$$=False13', 'LiteralString=$$=აკრიფეთ iframe-ის URL==14'),
                         ('Property=$$=True=$$=False15',
                          'LiteralString=$$=გადახვევის ზოლების დაშვება==16'),
                         ('Property=$$=True=$$=False17', 'LiteralString=$$=IFrame-ის პარამეტრები==18'),
                         ('Property=$$=False=$$=False19', 'LiteralString=$$=IFrame==20'),
                         ('ObjectExpression=$$=False=$$=True10', 'EMPTY'),
                         ('ObjectExpression=$$=False=$$=True10', 'EMPTY'),
                         ('ObjectExpression=$$=False=$$=True10', 'EMPTY'),
                         ('ObjectExpression=$$=False=$$=True10', 'EMPTY'),
                         ('ObjectExpression=$$=False=$$=True10', 'EMPTY'),
                         ('CallExpression=$$=False=$$=True2', 'EMPTY'),
                         ('CallExpression=$$=False=$$=True2', 'LiteralString=$$=iframe==8'),
                         ('CallExpression=$$=False=$$=True2', 'LiteralString=$$=ka==9'),
                         ('CallExpression=$$=False=$$=True2', 'EMPTY'),
                         ('ExpressionStatement=$$=False=$$=True1', 'EMPTY'),
                         ('Program=$$=False=$$=True0', 'EMPTY')]